    ERROR: Command errored out with exit status 1:
     command: /usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/bin/python /usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpvr2btrgt
         cwd: /tmp/pip-install-ky4aexos/polars
    Complete output (6 lines):
    
    Cargo, the Rust package manager, is not installed or is not on PATH.
    This package requires Rust and Cargo to compile extensions. Install it through
    the system's package manager or via https://rustup.rs/
    
    Checking for Rust toolchain....
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/bin/python /usr/local/easybuild-2019/easybuild/software/compiler/gcccore/8.3.0/python/3.7.4/lib/python3.7/site-packages/pip-19.2.3-py3.7.egg/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpvr2btrgt Check the logs for full command output.
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from scripts.twitter_processor import *
  File "/home/sunchuangyuh/A1/scripts/twitter_processor.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from scripts.twitter_processor import *
  File "/home/sunchuangyuh/A1/scripts/twitter_processor.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from scripts.twitter_processor import *
  File "/home/sunchuangyuh/A1/scripts/twitter_processor.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from scripts.twitter_processor import *
  File "/home/sunchuangyuh/A1/scripts/twitter_processor.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from scripts.twitter_processor import *
  File "/home/sunchuangyuh/A1/scripts/twitter_processor.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from scripts.twitter_processor import *
  File "/home/sunchuangyuh/A1/scripts/twitter_processor.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from scripts.twitter_processor import *
  File "/home/sunchuangyuh/A1/scripts/twitter_processor.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from scripts.twitter_processor import *
  File "/home/sunchuangyuh/A1/scripts/twitter_processor.py", line 7, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[31588,1],0]
  Exit code:    1
--------------------------------------------------------------------------
