Traceback (most recent call last):
  File "main.py", line 105, in <module>
    t2rdf = pd.concat(task2_dfs, axis=0, ignore_index=True)
NameError: name 'task2_dfs' is not defined
slurmstepd: error: *** JOB 45826324 ON spartan-bm087 CANCELLED AT 2023-03-26T16:00:02 DUE TO TIME LIMIT ***
